/* DO NOT EDIT THIS FILE - it is machine generated */
#include "external/windows/jni.h"
/* Header for class org_swdc_platforms_WindowsBinaryUtils */

#ifndef _Included_org_swdc_packager_core_FileUtils
#define _Included_org_swdc_packager_core_FileUtils
#ifdef __cplusplus
extern "C" {
#endif

	/*
	 * Class:     org_swdc_packager_core_FileUtils
	 * Method:    updateExecutableIcon
	 */
	JNIEXPORT jint JNICALL Java_org_swdc_packager_core_FileUtils_updateExecutableIcon
	(JNIEnv*, jclass, jstring, jobjectArray);

#ifdef __cplusplus
}
#endif
#endif
